apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secrets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-secrets-role
subjects:
- kind: ServiceAccount
  name: vault
  namespace: default
